# Generated by Django 4.2 on 2023-05-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Women')], default='M')),
                ('pasrepeat', models.CharField(max_length=20)),
            ],
        ),
    ]
